- Vagrantfile
- tests/test_models.py
- tests/test_routes.py
- Add PostgreSQL development library dependency in `Vagrant file`
- Create `test_models.py `and `test_routes.py`
> Update vagrant file

- requirements.txt
- service/__init__.py
- service/error_handlers.py
- service/models.py
- service/routes.py
- tests/factories.py
- tests/test_models.py
- tests/test_routes.py
Implemented a `POST` method for creating an inventory. Also set up the environment and templates for unit testing.
> Create create api

- service/models.py
- service/routes.py
- tests/test_models.py
- tests/test_routes.py
Add read api of inventory and its test cases.
> Create read api of inventory

- tests/test_error_handlers.py
Implement the following two unit tests to achieve 100% test coverage in `error_handlers.py`
- `test_method_not_supported`
- `test_internal_server_error`
> Add unit tests for methods in error_handlers.py

- service/models.py
- service/routes.py
- tests/test_models.py
- tests/test_routes.py
Implemented the route "/inventory?restock_level=<int>" with GET method.
Test Plan:
`nosetests`
```
-----------------------------------------------
service/__init__.py            24      3    88%
service/models.py              72      1    99%
service/routes.py              81      1    99%
-----------------------------------------------
TOTAL                         248      5    98%
----------------------------------------------------------------------
Ran 33 tests in 1.008s
OK
```
> Enhance query resource by restock level

- service/constants.py
- service/models.py
- service/routes.py
- tests/factories.py
- tests/test_models.py
- tests/test_routes.py
- Add query string to support
- `?product_id=<int:product_id>`
- `?condition=<str:condition>`
- `?quantity=<int:quantity>`
- `?restock_level=<int:restock_level>`
- Change the naming of `pid` to `product_id`
- Force the import order by running `isort **/*.py`
`nosetests`
output:
```
-----------------------------------------------
service/__init__.py            24      3    88%
service/constants.py            4      0   100%
service/models.py              79      1    99%
service/routes.py              93      1    99%
-----------------------------------------------
TOTAL                         271      5    98%
```
> Add query string support to the List function

- tests/test_routes.py
Previously, sometimes `test_get_inventory_by_query_available` failed. This PR is to fix this bug.
> Fix test_get_inventory_by_query_available

- Vagrantfile
- requirements.txt
Updated `Vagrantfile` for IBM Cloud.
> Update Vagrantfile and requirements.txt

- service/routes.py
- tests/test_routes.py
Close #88 
Also, remove unused imports.
> Fix activate/deactivate an inventory

- features/inventory.feature
- features/steps/inventory_steps.py
- requirements.txt
```bash
cd /vagrant
behave
```
You should see all pass.
> Create .feature file and accompanying steps.py

- service/routes.py
- tests/test_models.py
- tests/test_routes.py
Note that we'll gradually enhance our API with Flask-RESTX by adding new unit tests that call the new `API_BASE_URL = "/api/inventory"`
Test plan: `nosetests`
> Add flaskx for get_inventory method

- features/inventory.feature
> Enhance_UI_to_read_inventory

- features/inventory.feature
- features/steps/web_steps.py
- service/static/index.html
This PR is to add the search feature to our UI.
> Enhance UI to search inventory

- features/inventory.feature
- service/static/index.html
- Enhance UI to delete an inventory
- Add BDD for delete an inventory feature
```
Scenario: Delete an Inventory                                                                                     # features/inventory.feature:70
Given the following inventory                                                                                   # features/steps/inventory_steps.py:32 0.055s
| product_id | condition | quantity | restock_level | available |
| 1          | NEW       | 300      | 100           | True      |
| 4          | NEW       | 200      | 100           | True      |
When I visit the "Home Page"                                                                                    # features/steps/web_steps.py:14 0.030s
And I set the "Product ID" to "1" …
```
> Enhance UI to delete an inventory

- service/routes.py
- tests/test_routes.py
- Add flaskx for create method in route.py
- Add tests case for it
```
XML: /vagrant/unittests.xml
----------------------------------------------
service/__init__.py            24      4    83%
service/constants.py            8      0   100%
service/models.py              97      1    99%
service/routes.py             213      1    99%
----------------------------------------------
TOTAL                         413      6    99%
----------------------------------------------
Ran 59 tests in 1.717s
OK
```
> Add flaskx for create inventory

- service/routes.py
- tests/test_routes.py
- Add flaskx for activate and deactivate an inventory
- Add tests case for these two features
```
----------------------------------------------------------------------
XML: /vagrant/unittests.xml
-----------------------------------------------
service/__init__.py            24      4    83%
service/constants.py            8      0   100%
service/models.py              97      1    99%
service/routes.py             228      4    98%
-----------------------------------------------
TOTAL                         428      9    98%
----------------------------------------------------------------------
Ran 59 tests in 1.867s
OK
```
> Add flaskx for activate and deactivate an inventory

- service/routes.py
- service/static/js/rest_api.js
- tests/test_routes.py
- Add added amount feature to update inventory
- Add tests case for this feature
```
----------------------------------------------------------------------
XML: /vagrant/unittests.xml
-----------------------------------------------
service/__init__.py            24      4    83%
service/constants.py            8      0   100%
service/models.py              97      1    99%
service/routes.py             200      3    98%
-----------------------------------------------
TOTAL                         400      8    98%
----------------------------------------------------------------------
Ran 57 tests in 1.772s
OK
```
> Add added amount feature to update inventory

- features/inventory.feature
- service/static/index.html
- service/static/js/rest_api.js
This PR is to make our service support searching by quantity.
**Test Plan**
`behave`
```
1 feature passed, 0 failed, 0 skipped
6 scenarios passed, 0 failed, 0 skipped
93 steps passed, 0 failed, 0 skipped, 0 undefined
Took 0m2.449s
```
> enhance-ui-search-by-quantity

- features/inventory.feature
- service/static/index.html
Scenario: Activate an Inventory
When I visit the "Home Page"
And I set the "Product ID" to "8"
And I select "NEW" in the "Condition" dropdown
And I press the "Activate" button
Then I should see the message "Success"
When I visit the "Home Page"
And I set the "Product ID" to "8"
And I select "NEW" in the "Condition" dropdown
And I press the "Retrieve" button
Then I should see the message "Success"
And I should see "8" in the "Product ID" field
And I should see "NEW" in the "Condition" dropdown
And I should see "100" in the "Quantity" field
And I should see "100" in the "Restock Level" field
And I should see "True" in the "Available" dropdown
Scenario: Deactivate an Inventory
When I visit the "Home Page"
And I set the "Product ID" to "1"
And I select "NEW" in the "Condition" dropdown
And I …
> Enhance UI activate deactivate

- features/inventory.feature
- service/routes.py
- service/static/index.html
- service/static/js/rest_api.js
- tests/test_models.py
- tests/test_routes.py
This PR is to enhance the ui with adding amount feature
That's say if we have the following inventory in the database.
```
| product_id | condition | quantity | restock_level | available |
| 1          | NEW       | 300      | 100           | True      |
```
If we fill the add_amount value to 200 then click `add amount` button, the inventory will be updated as below.
```
| product_id | condition | quantity | restock_level | available |
| 1          | NEW       | 500      | 100           | True      |
```
**Test Plan**
`behave`
> enhance-ui-add-amount
